apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
  - path: ingress-host-patch.yaml

configMapGenerator:
  - name: nrp-aime-config
    behavior: merge
    envs:
      - config/app.env

secretGenerator:
  - name: nrp-aime-secrets
    behavior: replace
    envs:
      - config/secret.env

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: ghcr.io/your-org/nrp-aime-backend
    newTag: latest
  - name: ghcr.io/your-org/nrp-aime-frontend
    newTag: latest
