apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/backend-deployment.yaml
  - resources/backend-service.yaml
  - resources/aime-worker-deployment.yaml
  - resources/usage-worker-deployment.yaml
  - resources/frontend-deployment.yaml
  - resources/frontend-service.yaml
  - resources/ingress.yaml

patches:
  - path: ingress-host-patch.yaml
  - path: wait-for-db-database-url-patch.yaml

configMapGenerator:
  - name: nrp-aime-config
    envs:
      - config/app.env

secretGenerator:
  - name: nrp-aime-secrets
    envs:
      - config/secret.env

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: ghcr.io/your-org/nrp-aime-backend
    newName: ghcr.io/djw8605/nrp-aime-backend
    newTag: latest
  - name: ghcr.io/your-org/nrp-aime-frontend
    newName: ghcr.io/djw8605/nrp-aime-frontend
    newTag: latest
