apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: access-accounting

resources:
- resources/backend-deployment.yaml
- resources/backend-service.yaml
- resources/aime-worker-deployment.yaml
- resources/usage-worker-deployment.yaml
- resources/frontend-deployment.yaml
- resources/frontend-service.yaml
- resources/ingress.yaml
- secrets

configMapGenerator:
- envs:
  - config/app.env
  name: nrp-aime-config

generatorOptions:
  disableNameSuffixHash: true

images:
- name: ghcr.io/your-org/nrp-aime-backend
  newName: ghcr.io/djw8605/nrp-aime-backend
  newTag: 09b5e00b3c5ac4f770cc52b0eb355c34b0988c8e
- name: ghcr.io/your-org/nrp-aime-frontend
  newName: ghcr.io/djw8605/nrp-aime-frontend
  newTag: 09b5e00b3c5ac4f770cc52b0eb355c34b0988c8e
