apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: access-accounting

resources:
- resources/backend-deployment.yaml
- resources/backend-service.yaml
- resources/aime-worker-deployment.yaml
- resources/usage-worker-deployment.yaml
- resources/frontend-deployment.yaml
- resources/frontend-service.yaml
- resources/ingress.yaml
- secrets

configMapGenerator:
- envs:
  - config/app.env
  name: nrp-aime-config

generatorOptions:
  disableNameSuffixHash: true

images:
- name: ghcr.io/your-org/nrp-aime-backend
  newName: ghcr.io/djw8605/nrp-aime-backend
  newTag: b599e9082e9122b9951450ec1fe6ed52e2ea6930
- name: ghcr.io/your-org/nrp-aime-frontend
  newName: ghcr.io/djw8605/nrp-aime-frontend
  newTag: b599e9082e9122b9951450ec1fe6ed52e2ea6930
